try {
  a;
} catch (e) {
  console.log(`Err: ${e}`);
}

console.log('a');
